### ISSUE TITLE
Check all links

### ISSUE THREAD

**Issue by bernalde** [SECQUOIA/SECQUOIA.github.io#1]
@ZedongPeng please make sure all links are working. I would suggest removing the numbering in the sections.
Also if @pedromxavier has any input on visuals, we would greatly appreciate them.

**Comment by ZedongPeng** [comment]
The sections are placed in alphabetical order. Since we want several sections to be on the top, numbering is the simplest way.

**Comment by bernalde** [comment]
Good point, please move the news after the members
