### ISSUE TITLE
LinkedIn link does not work

### ISSUE THREAD

**Issue by ZedongPeng** [SECQUOIA/SECQUOIA.github.io#18]
On the members page, @anurag-r20 's LinkedIn link seems not working.
It currently navigates to `https://secquoia.github.io/www.linkedin.com/in/anurag-r`.
I think `https://` is missed.
https://github.com/SECQUOIA/SECQUOIA.github.io/blob/1b75df045415f383082f48210754d23b4d44f463/2-members.md?plain=1#L95

**Comment by bernalde** [comment]
@anurag-r20 please create a PR to address this issue.
