### ISSUE TITLE
News of arrival

### ISSUE THREAD

**Issue by bernalde** [SECQUOIA/SECQUOIA.github.io#24]
Dear @tristantc and @deepquantum88 , you arrived in our group and haven't yet posted any news in it. Do you plan to?

**Comment by ZedongPeng** [comment]
Here is an example of adding news on the group website, FYI. https://github.com/SECQUOIA/SECQUOIA.github.io/pull/20

**Comment by tristantc** [comment]
> Dear @tristantc and @deepquantum88 , you arrived in our group and haven't yet posted any news in it. Do you plan to?
@bernalde rest assured I am on it.

**Comment by tristantc** [comment]
> Here is an example of adding news on the group website, FYI. #20

Quite handy.
Much appreciated, @ZedongPeng!

**Comment by bernalde** [comment]
@tristantc you pushed the changes directly to the main branch, this is why I didn't get a notification. For this, next time please create a Pull request.
@deepquantum88 are you making a PR?

**Comment by ZedongPeng** [comment]
Hi @tristantc . There is a typo in your arrival news.
<img width="1043" alt="image" src="https://github.com/SECQUOIA/SECQUOIA.github.io/assets/15854830/0a46991c-2e9b-41b4-b44f-47d2a7404a62">

**Comment by tristantc** [comment]
> Hi @tristantc . There is a typo in your arrival news. <img alt="image" width="1043" src="https://private-user-images.githubusercontent.com/15854830/306043462-0a46991c-2e9b-41b4-b44f-47d2a7404a62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNzQwMzYsIm5iZiI6MTcwODM3MzczNiwicGF0aCI6Ii8xNTg1NDgzMC8zMDYwNDM0NjItMGE0Njk5MWMtMmU5Yi00MWI0LWI0NGYtNDdkMmE3NDA0YTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDIwMTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0N2Q3NTUwZTcyODJlMGVlMzU0ZGNlM2RiYjFhZWYxNmJlM2YyMmMxM2QwYjk1NDBjNzI4MWQ0Mjk2NTM1NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ntDdo9Ekt2qgAJmhXG-kdbUo38CFyT0fYb7tRimrM8">

@ZedongPeng  tristantc/issue24 is the correct branch

**Comment by bernalde** [comment]
I suppose that there is not going to be news on arrival, yet the typo issue is still there (#28 ), and there is another upcoming post based on the participation at AIChE @tristantc @AlbertLee125 .
Please address this
