### ISSUE TITLE
Add ORCID to each one of the profiles

### ISSUE THREAD

**Issue by bernalde** [SECQUOIA/SECQUOIA.github.io#33]
Add ORCID to each one of the profiles

- [x] @bernalde 
- [x] @ZedongPeng 
- [ ] @tristantc 
- [ ] @Hamtabardool (depending on #34 )
- [x] @AlbertLee125 
- [ ] @anurag-r20 
- [x] @parkyr 
- [ ] @pedromxavier 
- [x] @andres9403 
- [x] @jsrodriguezf

**Comment by parkyr** [comment]
created a branch for this, pull request:
#37
