### ISSUE TITLE
Update news

### ISSUE THREAD

**Issue by ZedongPeng** [SECQUOIA/SECQUOIA.github.io#38]
The news section on our website has not been updated for some time. We need to refresh it with the latest updates, aligning it with our recent LinkedIn posts. Include, but not limited to, the following list:

- [ ] Quantum Optimization Working Group Meeting at ZIB @pedromxavier 
- [ ] MIP workshop @AlbertLee125 @anurag-r20 
- [ ] ESCAPE / PSE @ZedongPeng 
- [x] Welcome new members @parkyr and @anurag-r20 
- [ ] 2024 INFORMS Optimization Society Conference

**Comment by bernalde** [comment]
After discussion today at the group meeting, we decided to not include all the conference news and only have the major updates here.
Let's rather link to LinkedIn and clean it up a little bit
